addons:
  apt:
    update: true
    packages: git wget libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache libffi-dev libssl-dev

before_script:
   - pushd ~
   - git clone --recursive --branch release/v4.1 https://github.com/espressif/esp-idf.git
   - cd esp-idf
   - ./install.sh
   - popd

language: minimal

script:
   - idf.py build
